### ISSUE TITLE
翻译错误，

### ISSUE THREAD

**Issue by gyp03** [LearnSolid/solid-docs#7]
《SoLiD 具体技术细节》，那章下面的总结里--》它提供分散身份验证、分散的数据管理、  以库    和 Web 组件形式提供的开发人员支持   ，，，，，这个以库翻译错了，更正一下吧

**Comment by linonetwo** [comment]
没错啊，by library，你觉得应该是啥

**Comment by qhduan** [comment]
猜测可能是想到日语了～～

或者改成：使用库或web组件形式

**Comment by linonetwo** [comment]
误会成行く了？那我改一下吧
